import MaterialCommunityIcons from 'react-native-vector-icons/MaterialCommunityIcons';

export const categoryIcons: any = {
    'Food & Drink': <MaterialCommunityIcons name="food" size={30} color="red" />,
    'Shopping': <MaterialCommunityIcons name="cart" size={30} color="blue" />,
    'Transport': <MaterialCommunityIcons name="bus" size={30} color="#929222" />,
    'Home': <MaterialCommunityIcons name="home" size={30} color="green" />,
    'Bills & Fees': <MaterialCommunityIcons name="credit-card" size={30} color="orange" />,
    'Entertainment': <MaterialCommunityIcons name="gamepad-variant" size={30} color="purple" />,
    'Car': <MaterialCommunityIcons name="car" size={30} color="pink" />,
    'Travel': <MaterialCommunityIcons name="airplane" size={30} color="cyan" />,
    'Family ': <MaterialCommunityIcons name="account-group" size={30} color="teal" />,
    'Healthcare': <MaterialCommunityIcons name="hospital" size={30} color="brown" />,
    'Education': <MaterialCommunityIcons name="school" size={30} color="#af00ff" />,
    'Groceries': <MaterialCommunityIcons name="basket" size={30} color="indigo" />,
    'Gifts': <MaterialCommunityIcons name="gift" size={30} color="violet" />,
    'Sport & Hobby': <MaterialCommunityIcons name="soccer" size={30} color="magenta" />,
    'Beauty': <MaterialCommunityIcons name="face" size={30} color="grey" />,
    'Work': <MaterialCommunityIcons name="briefcase" size={30} color="navy" />,
    'Other': <MaterialCommunityIcons name="dots-horizontal" size={30} color="maroon" />,
    // // 
    'Salary': <MaterialCommunityIcons name="currency-usd" size={30} color="red" />,
    'Business': <MaterialCommunityIcons name="briefcase" size={30} color="blue" />,
    'Giftss': <MaterialCommunityIcons name="gift" size={30} color="green" />,
    'Extra Income': <MaterialCommunityIcons name="cash-multiple" size={30} color="orange" />,
    'Loan': <MaterialCommunityIcons name="bank" size={30} color="pink" />,
    'Parental Leave': <MaterialCommunityIcons name="baby" size={30} color="#73b5b5" />,
    'Insurance': <MaterialCommunityIcons name="shield-account" size={30} color="brown" />,
    'Otherr': <MaterialCommunityIcons name="dots-horizontal" size={30} color="grey" />,
}
